set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

set_property PACKAGE_PIN W19 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports start]

set_property PACKAGE_PIN V17 [get_ports {x1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x1[0]}]
set_property PACKAGE_PIN V16 [get_ports {x1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x1[1]}]
set_property PACKAGE_PIN W16 [get_ports {x1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x1[2]}]
set_property PACKAGE_PIN W17 [get_ports {x1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x1[3]}]
set_property PACKAGE_PIN W15 [get_ports {x1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x1[4]}]
set_property PACKAGE_PIN V15 [get_ports {x1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x1[5]}]
set_property PACKAGE_PIN W14 [get_ports {x1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x1[6]}]
set_property PACKAGE_PIN W13 [get_ports {x1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x1[7]}]

set_property PACKAGE_PIN V2 [get_ports {x2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x2[0]}]
set_property PACKAGE_PIN T3 [get_ports {x2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x2[1]}]
set_property PACKAGE_PIN T2 [get_ports {x2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x2[2]}]
set_property PACKAGE_PIN R3 [get_ports {x2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x2[3]}]
set_property PACKAGE_PIN W2 [get_ports {x2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x2[4]}]
set_property PACKAGE_PIN U1 [get_ports {x2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x2[5]}]
set_property PACKAGE_PIN T1 [get_ports {x2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x2[6]}]
set_property PACKAGE_PIN R2 [get_ports {x2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {x2[7]}]
# LEDs

set_property PACKAGE_PIN U16 [get_ports {out1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out1[0]}]
set_property PACKAGE_PIN E19 [get_ports {out1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out1[1]}]
set_property PACKAGE_PIN U19 [get_ports {out1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out1[2]}]
set_property PACKAGE_PIN V19 [get_ports {out1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out1[3]}]
set_property PACKAGE_PIN W18 [get_ports {out1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out1[4]}]
set_property PACKAGE_PIN U15 [get_ports {out1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out1[5]}]
set_property PACKAGE_PIN U14 [get_ports {out1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out1[6]}]
set_property PACKAGE_PIN V14 [get_ports {out1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out1[7]}]

set_property PACKAGE_PIN L1 [get_ports {out2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out2[0]}]
set_property PACKAGE_PIN P1 [get_ports {out2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out2[1]}]
set_property PACKAGE_PIN N3 [get_ports {out2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out2[2]}]
